### ISSUE TITLE
add timestamp in video stream

### ISSUE THREAD

**Issue by allen2000github** [kclyu/rpi-webrtc-streamer#33]
Hi kclyu,

Thanks for this great work. I wonder whether an optional timestamp could be added into video stream? It is helpful to make me know whether the stream is live or not when under some static scene.

BR,

**Comment by kclyu** [comment]
Hi,

RWS video streaming uses the function to adjust resolution according to Bandwidth Estimation, so 'Video annotation' function is not supported in rws  RTC video streaming yet. It is not supported because it does not yet implement the part that adjusts the font size whenever the video resolution is changed.

Currently motion detection with fixed resolution is only supported when saving video file.

After adding the function, I will post it in this article and close it.

BR,
