### ISSUE TITLE
Host Architecture arm is not supported

### ISSUE THREAD

**Issue by varunsuresh2912** [kclyu/rpi-webrtc-streamer#42]
While running gclient sync, getting 'ERROR: Command '/usr/bin/python src/third_party/binutils/download.py' returned non-zero exit status 1 in /home/pi/Workspace/webrtc

**Comment by kclyu** [comment]
WebRTC native code package can be downloaded and compiled on Ubuntu Linux . You will not be able to compile it because you can not download it directly to Raspberry PI.

Please refer to the [README_building](https://github.com/kclyu/rpi-webrtc-streamer/blob/master/README_building.md) document.

Follow the link to the official WebRTC.org [documentation](https://webrtc.org/native-code/development/).
