### ISSUE TITLE
Stream to multiple users at the same time

### ISSUE THREAD

**Issue by peymanh** [kclyu/rpi-webrtc-streamer#50]
Hi. Thanks for the great Repo. I want to use this package to stream the pi camera frames to multiple users at the same time. As far I see, there is a limitation of only one client to access the stream. Is there any way to increase this number? Is it a hardware-related constraint?
Thanks in advance

**Comment by kclyu** [comment]
RWS was primarily intended to allow video/audio to be transmitted with minimal delay in a peer-to-peer configuration, and is currently configured to do so. Currently, only one session is supported because the camera adjusts the frame//fps of the video to suit the situation of the peer during video transmission.

The one-to-many video broadcasting you mentioned is not currently supported, but I think it's the part that needs to be added later. The broadcasting architecture has not yet been fixed, but it seems to be using a media server (SFU or MCU). This part replaces this [Do I Need a Media Server for a One-to-Many WebRTC Broadcast?](https://bloggeek.me/media-server-for-webrtc-broadcast/)   because it is not easy to answer.
