### ISSUE TITLE
Does rpi-webrtc-streamer supports data channels?

### ISSUE THREAD

**Issue by tartavull** [kclyu/rpi-webrtc-streamer#75]
Does rpi-webrtc-streamer supports data channels?

**Comment by kclyu** [comment]
Datachannel is not used in RWS, so Datachannel is not implemented. I am wondering what the purpose of Datachannel in RWS is, even if it supports Datachannel.

**Comment by kclyu** [comment]
Please reopen the issue again if you have an issue.

**Comment by tartavull** [comment]
Hey @kclyu,
   if you have a camera which can be oriented using a motor, you could use a datachannel to set the position.

**Comment by kclyu** [comment]
The browser datachannel uses javascript, so it can be useful for many purposes. However, since rws creates a PeerConnection with cpp, the DataChannel must also be created in cpp, and the ability to use datachannel must also be developed together with cpp. In a nutshell, it is not possible to use it freely like javascript of browser.

I know what you are going to do, but it seems to be a bad idea to include functionality to the app you are developing  in your rws. It seems to be the only way to modify the source directly if necessary.

**Comment by tartavull** [comment]
That makes sense, thank you @kclyu !

**Comment by miguelwon** [comment]
Hi,
Any change that this could be implemented? Like @tartavull wrote, a data channel would be great for controlling remotely the camera and other servos. I think it would be enough for the data channel output to be sent to stdout and then parse it with some python script.

**Comment by kclyu** [comment]
So far, the idea of supporting DataChannel has not changed.

I don't know if it's a good idea to use log message to pass specific data to another process.
If I implement the necessary functions above, I will consider the implementation method with the following design.

In order to exchange the current signaling message, the WebSocket connection is maintained during streaming. I will not explain why WebSocket keeps connecting because it is not related to this issue. I  will create a new JSON message type that transmits a message to a specific UDP/TCP port in the signaling message and link it with other processes.

1. open UDP/TCP port which is bind to localhost only.
2. If it is a JSON message that delivers the message to another process, the message is sent to a specific socket.
3. If there is a JSON event/response message in the socket for message transmission, send this message to the client via WebSocket.

So far, it is a method for interworking with other processes by modifying the signaling websocket of RWS. However, this method is not recommended because it is a method of another message protocol on the signaling websocket. 

Another method is to place nginx between client and rws,  WebSocket for RWS signaling uses nginx Reverse Proxy, and websocket or http is used for interworking with other hardware control processes. 

The implementation method seems to be sufficient for using any additional module  or  rws source modifications.

**Comment by miguelwon** [comment]
Ok, thanks.  Small feedback on my recent experience: I have tried webrtc with Gstreamer and sending commands (jsons strings) through the same WebSocket used for signaling.  It didn't work very well for the scenario where I need to send commands fast and constantly. It was hanging quite frequently. With a DataChannel I do not see that hanging problem.

**Comment by jonspieg** [comment]
I must say that adding DataChannel support to RWS would be highly beneficial, since the data transfer is peer to peer and the latency should be very low.  Instead of building the rpi side of the application right into RWS, one can go the UV4L route and expose the DataChannel through a unix domain socket so that any application (in any language) can access it.
I'm currently in the process of moving from UV4L to RWS and this is one of the main hurdles.
